# Generated by Django 3.2.21 on 2023-09-26 15:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio4', '0003_commentlikes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentLikes',
            new_name='CommentLike',
        ),
    ]
