# Generated by Django 3.2.21 on 2023-09-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio4', '0005_auto_20230926_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
