# Generated by Django 3.2.21 on 2023-09-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio4', '0009_rename_post_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='heading',
            field=models.CharField(default='exit', max_length=40),
            preserve_default=False,
        ),
    ]
