# Generated by Django 3.2.21 on 2023-10-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio4', '0010_post_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlike',
            name='author',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
