# Generated by Django 3.2.21 on 2023-10-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio4', '0015_auto_20231004_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, to='portfolio4.Category'),
        ),
    ]
