# Generated by Django 3.2.21 on 2023-10-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio4', '0016_alter_post_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['creation_time']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-creation_time']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='creationTime',
            new_name='creation_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creationTime',
            new_name='creation_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='lastModified',
            new_name='last_modified',
        ),
    ]
