# Generated by Django 3.2.21 on 2023-10-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio4', '0019_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
