# Generated by Django 3.2.21 on 2023-10-11 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio4', '0021_extendeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='author_comment', to='portfolio4.extendeduser'),
        ),
    ]
