# Generated by Django 3.2.21 on 2023-10-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio4', '0023_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
